### YamlMime:ManagedReference
items:
- uid: PipelineTFM.Configuration
  commentId: N:PipelineTFM.Configuration
  id: PipelineTFM.Configuration
  children:
  - PipelineTFM.Configuration.AppSettingsConfiguration
  - PipelineTFM.Configuration.AutoMapperStartup
  - PipelineTFM.Configuration.ConfigurationHelper
  - PipelineTFM.Configuration.DatabaseConfiguration
  - PipelineTFM.Configuration.ProblemDetailsStartup
  - PipelineTFM.Configuration.RepositoryStartup
  - PipelineTFM.Configuration.SerilogConfiguration
  - PipelineTFM.Configuration.ServiceStartup
  - PipelineTFM.Configuration.SwaggerConfiguration
  - PipelineTFM.Configuration.WebConfiguration
  langs:
  - csharp
  - vb
  name: PipelineTFM.Configuration
  nameWithType: PipelineTFM.Configuration
  fullName: PipelineTFM.Configuration
  type: Namespace
  assemblies:
  - PipelineTFM
references:
- uid: PipelineTFM.Configuration.AppSettingsConfiguration
  commentId: T:PipelineTFM.Configuration.AppSettingsConfiguration
  href: PipelineTFM.Configuration.AppSettingsConfiguration.html
  name: AppSettingsConfiguration
  nameWithType: AppSettingsConfiguration
  fullName: PipelineTFM.Configuration.AppSettingsConfiguration
- uid: PipelineTFM.Configuration.AutoMapperStartup
  commentId: T:PipelineTFM.Configuration.AutoMapperStartup
  href: PipelineTFM.Configuration.AutoMapperStartup.html
  name: AutoMapperStartup
  nameWithType: AutoMapperStartup
  fullName: PipelineTFM.Configuration.AutoMapperStartup
- uid: PipelineTFM.Configuration.ConfigurationHelper
  commentId: T:PipelineTFM.Configuration.ConfigurationHelper
  href: PipelineTFM.Configuration.ConfigurationHelper.html
  name: ConfigurationHelper
  nameWithType: ConfigurationHelper
  fullName: PipelineTFM.Configuration.ConfigurationHelper
- uid: PipelineTFM.Configuration.DatabaseConfiguration
  commentId: T:PipelineTFM.Configuration.DatabaseConfiguration
  href: PipelineTFM.Configuration.DatabaseConfiguration.html
  name: DatabaseConfiguration
  nameWithType: DatabaseConfiguration
  fullName: PipelineTFM.Configuration.DatabaseConfiguration
- uid: PipelineTFM.Configuration.SerilogConfiguration
  commentId: T:PipelineTFM.Configuration.SerilogConfiguration
  href: PipelineTFM.Configuration.SerilogConfiguration.html
  name: SerilogConfiguration
  nameWithType: SerilogConfiguration
  fullName: PipelineTFM.Configuration.SerilogConfiguration
- uid: PipelineTFM.Configuration.WebConfiguration
  commentId: T:PipelineTFM.Configuration.WebConfiguration
  href: PipelineTFM.Configuration.WebConfiguration.html
  name: WebConfiguration
  nameWithType: WebConfiguration
  fullName: PipelineTFM.Configuration.WebConfiguration
- uid: PipelineTFM.Configuration.ProblemDetailsStartup
  commentId: T:PipelineTFM.Configuration.ProblemDetailsStartup
  href: PipelineTFM.Configuration.ProblemDetailsStartup.html
  name: ProblemDetailsStartup
  nameWithType: ProblemDetailsStartup
  fullName: PipelineTFM.Configuration.ProblemDetailsStartup
- uid: PipelineTFM.Configuration.RepositoryStartup
  commentId: T:PipelineTFM.Configuration.RepositoryStartup
  href: PipelineTFM.Configuration.RepositoryStartup.html
  name: RepositoryStartup
  nameWithType: RepositoryStartup
  fullName: PipelineTFM.Configuration.RepositoryStartup
- uid: PipelineTFM.Configuration.ServiceStartup
  commentId: T:PipelineTFM.Configuration.ServiceStartup
  href: PipelineTFM.Configuration.ServiceStartup.html
  name: ServiceStartup
  nameWithType: ServiceStartup
  fullName: PipelineTFM.Configuration.ServiceStartup
- uid: PipelineTFM.Configuration.SwaggerConfiguration
  commentId: T:PipelineTFM.Configuration.SwaggerConfiguration
  href: PipelineTFM.Configuration.SwaggerConfiguration.html
  name: SwaggerConfiguration
  nameWithType: SwaggerConfiguration
  fullName: PipelineTFM.Configuration.SwaggerConfiguration
