### YamlMime:ManagedReference
items:
- uid: PipelineTFM.Configuration.ConfigurationHelper
  commentId: T:PipelineTFM.Configuration.ConfigurationHelper
  id: ConfigurationHelper
  parent: PipelineTFM.Configuration
  children:
  - PipelineTFM.Configuration.ConfigurationHelper.GetOptions``1(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  langs:
  - csharp
  - vb
  name: ConfigurationHelper
  nameWithType: ConfigurationHelper
  fullName: PipelineTFM.Configuration.ConfigurationHelper
  type: Class
  source:
    remote:
      path: src/PipelineTFM/Configuration/ConfigurationHelper.cs
      branch: TFM-11
      repo: https://github.com/UNamurCSFaculty/2324_INFOM126_GROUPE_09
    id: ConfigurationHelper
    path: ../src/PipelineTFM/Configuration/ConfigurationHelper.cs
    startLine: 4
  assemblies:
  - PipelineTFM
  namespace: PipelineTFM.Configuration
  syntax:
    content: public static class ConfigurationHelper
    content.vb: Public Module ConfigurationHelper
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: PipelineTFM.Configuration.ConfigurationHelper.GetOptions``1(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  commentId: M:PipelineTFM.Configuration.ConfigurationHelper.GetOptions``1(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  id: GetOptions``1(Microsoft.Extensions.Configuration.IConfiguration,System.String)
  isExtensionMethod: true
  parent: PipelineTFM.Configuration.ConfigurationHelper
  langs:
  - csharp
  - vb
  name: GetOptions<TModel>(IConfiguration, string)
  nameWithType: ConfigurationHelper.GetOptions<TModel>(IConfiguration, string)
  fullName: PipelineTFM.Configuration.ConfigurationHelper.GetOptions<TModel>(Microsoft.Extensions.Configuration.IConfiguration, string)
  type: Method
  source:
    remote:
      path: src/PipelineTFM/Configuration/ConfigurationHelper.cs
      branch: TFM-11
      repo: https://github.com/UNamurCSFaculty/2324_INFOM126_GROUPE_09
    id: GetOptions
    path: ../src/PipelineTFM/Configuration/ConfigurationHelper.cs
    startLine: 6
  assemblies:
  - PipelineTFM
  namespace: PipelineTFM.Configuration
  syntax:
    content: 'public static TModel GetOptions<TModel>(this IConfiguration configuration, string section) where TModel : new()'
    parameters:
    - id: configuration
      type: Microsoft.Extensions.Configuration.IConfiguration
    - id: section
      type: System.String
    typeParameters:
    - id: TModel
    return:
      type: '{TModel}'
    content.vb: Public Shared Function GetOptions(Of TModel As New)(configuration As IConfiguration, section As String) As TModel
  overload: PipelineTFM.Configuration.ConfigurationHelper.GetOptions*
  nameWithType.vb: ConfigurationHelper.GetOptions(Of TModel)(IConfiguration, String)
  fullName.vb: PipelineTFM.Configuration.ConfigurationHelper.GetOptions(Of TModel)(Microsoft.Extensions.Configuration.IConfiguration, String)
  name.vb: GetOptions(Of TModel)(IConfiguration, String)
references:
- uid: PipelineTFM.Configuration
  commentId: N:PipelineTFM.Configuration
  href: PipelineTFM.html
  name: PipelineTFM.Configuration
  nameWithType: PipelineTFM.Configuration
  fullName: PipelineTFM.Configuration
  spec.csharp:
  - uid: PipelineTFM
    name: PipelineTFM
    href: PipelineTFM.html
  - name: .
  - uid: PipelineTFM.Configuration
    name: Configuration
    href: PipelineTFM.Configuration.html
  spec.vb:
  - uid: PipelineTFM
    name: PipelineTFM
    href: PipelineTFM.html
  - name: .
  - uid: PipelineTFM.Configuration
    name: Configuration
    href: PipelineTFM.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: PipelineTFM.Configuration.ConfigurationHelper.GetOptions*
  commentId: Overload:PipelineTFM.Configuration.ConfigurationHelper.GetOptions
  href: PipelineTFM.Configuration.ConfigurationHelper.html#PipelineTFM_Configuration_ConfigurationHelper_GetOptions__1_Microsoft_Extensions_Configuration_IConfiguration_System_String_
  name: GetOptions
  nameWithType: ConfigurationHelper.GetOptions
  fullName: PipelineTFM.Configuration.ConfigurationHelper.GetOptions
- uid: Microsoft.Extensions.Configuration.IConfiguration
  commentId: T:Microsoft.Extensions.Configuration.IConfiguration
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.configuration.iconfiguration
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Extensions.Configuration.IConfiguration
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: '{TModel}'
  commentId: '!:TModel'
  definition: TModel
  name: TModel
  nameWithType: TModel
  fullName: TModel
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.configuration
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Configuration
    name: Configuration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.configuration
- uid: TModel
  commentId: '!:TModel'
  name: TModel
  nameWithType: TModel
  fullName: TModel
