### YamlMime:ManagedReference
items:
- uid: PipelineTFM.Configuration.AutoMapper
  commentId: N:PipelineTFM.Configuration.AutoMapper
  id: PipelineTFM.Configuration.AutoMapper
  children:
  - PipelineTFM.Configuration.AutoMapper.AutoMapperProfile
  langs:
  - csharp
  - vb
  name: PipelineTFM.Configuration.AutoMapper
  nameWithType: PipelineTFM.Configuration.AutoMapper
  fullName: PipelineTFM.Configuration.AutoMapper
  type: Namespace
  assemblies:
  - PipelineTFM
references:
- uid: PipelineTFM.Configuration.AutoMapper.AutoMapperProfile
  commentId: T:PipelineTFM.Configuration.AutoMapper.AutoMapperProfile
  href: PipelineTFM.Configuration.AutoMapper.AutoMapperProfile.html
  name: AutoMapperProfile
  nameWithType: AutoMapperProfile
  fullName: PipelineTFM.Configuration.AutoMapper.AutoMapperProfile
