name: PipelineTFM
services:
  app:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: Dockerfile-Back
    ports:
      - 5000:80
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    restart: unless-stopped
    extends:
      file: ./postgresql-prod.yml
      service: postgresql