name: Daily Build and Test
on:
  schedule:
    #- cron: '0 0 * * *'  # Run daily at midnight UTC
    - cron: '*/5 * * * *'  # Run every 5 minutes to test it

jobs:
  call-workflow:
    uses: UNamurCSFaculty/2324_INFOM126_GROUPE_09/.github/workflows/dotnet.yml
