name: Daily Build and Test
on:
  schedule:
    #- cron: '0 0 * * *'  # Run daily at midnight UTC
    - cron: '0 */6 * * *'  # Run every 6 hours to test it

jobs:
  call-workflow:
    uses: ./.github/workflows/dotnet.yml
