name: Deploy TFM app

on:
  push:
    branches: ["TFM-12"]
#  pull_request:
#    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
          
      - name: Update project
        run: |
          ssh staging 'cd ${{ secrets.SSH_BUILD_TFM_DIR }} && git pull origin main'
          
      - name: Stop current service
        run: |
          ssh staging 'docker compose -f ./docker/app.yml stop'
          
      - name: Build
        run: |
          ssh staging 'docker compose -f ./docker/app.yml build'

      - name: Start new app
        run: |
          ssh staging 'docker compose -f ./docker/app.yml up -d'