name: Deploy Documentation

on:
  push:
    branches:
      - main
      - TFM-11


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up .NET Core for C# documentation
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Install Compodoc
    - name: Install Compodoc
      run: npm install -g @compodoc/compodoc

    # Install DocFX
    - name: Install DocFX
      run: |
        wget https://github.com/dotnet/docfx/releases/download/v2.74.1/docfx-linux-x64-v2.74.1.zip
        mkdir docfx
        unzip docfx-linux-x64-v2.74.1.zip -d docfx

    # Generate C# Documentation
    - name: Generate C# Documentation
      run: |
        docfx/docfx docfx.json
        mv _site docs/csharp-docs

    # Generate Angular Documentation
    - name: Generate Angular Documentation
      run: |
        compodoc -p src/PipelineTFM/ClientApp/tsconfig.json -d ./docs/angular-docs

    # Install TypeDoc
    - name: Install TypeDoc
      run: npm install -g typedoc

    # Generate TypeScript Documentation
    - name: Generate TypeScript Documentation
      run: |
        typedoc --tsconfig src/PipelineTFM/ClientApp/tsconfig.json --out ./docs/ts-docs

    # Create index.html to link to all documentations
    - name: Create Index HTML
      run: |
        echo "<html><head><title>Documentation Index</title></head><body><h1>Documentation</h1><ul><li><a href='csharp-docs/README.html'>C# Documentation</a></li><li><a href='angular-docs/index.html'>Angular Documentation</a></li><li><a href='ts-docs/index.html'>TypeScript Documentation</a></li></ul></body></html>" > docs/index.html

    # Deploy to GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_GITHUB_PAGES_DOC }}
        publish_dir: ./docs
        publish_branch: gh-pages  # Pushes to the gh-pages branch
