name: Deploy Documentation

on:
  push:
    branches:
      - main
      - TFM-11


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.x

    - name: Install Compodoc
      run: npm install -g @compodoc/compodoc

    - name: Create pages directory
      run: mkdir github_pages_tmp

    - name: Install DocFX
      run: dotnet tool update -g docfx
      #run: |
      #  wget https://github.com/dotnet/docfx/releases/download/v2.74.1/docfx-linux-x64-v2.74.1.zip
      #  mkdir docfx_app
      #  unzip docfx-linux-x64-v2.74.1.zip -d docfx_app

    - name: Generate C# Documentation
      run: |
        #docfx_app/docfx docs/docfx/docfx.json
        docfx docs/docfx/docfx.json
        mv docs/docfx/_site github_pages_tmp/cs-docs

    - name: Generate Angular Documentation
      run: |
        compodoc -p src/PipelineTFM/ClientApp/tsconfig.json -d github_pages_tmp/angular-docs

    - name: Copy landing page
      run: cp -R docs/landing_page_doc/* github_pages_tmp

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_GITHUB_PAGES_DOC }}
        publish_dir: github_pages_tmp
        publish_branch: gh-pages  # Pushes to the gh-pages branch
