name: Deploy Documentation

on:
  push:
    branches:
      - main
      - TFM-11


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install Compodoc
      run: npm install -g @compodoc/compodoc

    - name: Install DocFX
      run: |
        wget https://github.com/dotnet/docfx/releases/download/v2.74.1/docfx-linux-x64-v2.74.1.zip
        mkdir docfx
        unzip docfx-linux-x64-v2.74.1.zip -d docfx

    - name: Generate C# Documentation
      run: |
        docfx/docfx docfx.json
        mv _site docs/csharp-docs

    - name: Generate Angular Documentation
      run: |
        compodoc -p src/PipelineTFM/ClientApp/tsconfig.json -d ./docs/angular-docs

    - name: Install TypeDoc
      run: npm install -g typedoc

    - name: Generate TypeScript Documentation
      run: |
        typedoc --tsconfig src/PipelineTFM/ClientApp/tsconfig.json --out ./docs/ts-docs

    - name: Copy landing page
      run: cp -R landing_page_doc ./docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_GITHUB_PAGES_DOC }}
        publish_dir: ./docs
        publish_branch: gh-pages  # Pushes to the gh-pages branch
