name: Deploy Documentation

on:
  push:
    branches:
      - main
      - TFM-11


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up .NET Core for C# documentation
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    # Install Compodoc
    - name: Install Compodoc
      run: npm install -g @compodoc/compodoc

    # TODO - Generate C# Documentation
    #- name: Generate C# Documentation
    #  run: |
    #

    # Generate Angular Documentation
    - name: Generate Angular Documentation
      run: |
        compodoc -p src/PipelineTFM/ClientApp/tsconfig.json

    # Deploy to GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_GITHUB_PAGES_DOC }}
        publish_dir: ./docs
        publish_branch: gh-pages  # Pushes to the gh-pages branch
