name: Code Format

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dotnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Check C# format
        run: dotnet format --verify-no-changes

  angular:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install Dev dependencies
        run: npm install -D
      - name: Check ClientApp format
        run: npm run prettier:check-ci
        working-directory: src/PipelineTFM/ClientApp